### PR TITLE
deleted version file

### LINKED ISSUE #35: Remove version file
I noticed we never removed this file from @SteSeg 's PR : https://github.com/LIBRA-project/libra-toolbox/pull/23/files

https://github.com/LIBRA-project/libra-toolbox/blob/main/libra_toolbox/_version.py

Needs to be removed!

### PR DESCRIPTION
**Pull request by veliki-filozof**
Fixes #35, removing the version file that is not needed

### CODE REVIEW

**Comment by veliki-filozof** [comment]
Hai @RemDelaporteMathurin maybe merge this please and thank you

**Comment by veliki-filozof** [comment]
Spamming @RemDelaporteMathurin because I'm very impatient

**Comment by veliki-filozof** [comment]
Cmon man @RemDelaporteMathurin WHERE ARE YOU

**Review by RemDelaporteMathurin — APPROVED** [review]
Thank you so much 🎉 🚀

**Comment by veliki-filozof** [comment]
Woop Woop Thanks @RemDelaporteMathurin 🥂

**Pull request merged**
